### ISSUE TITLE
Not fully transparent panel

### ISSUE THREAD

**Issue by nickdex** [avivace/Arc-T#1]
Hi, I used your [dotfiles](https://github.com/avivace/dotfiles) to have same i3 config. When I applied Arc-T, there is a small section at top that doesn't turn transparent. [image]

![image](https://user-images.githubusercontent.com/8512967/48299002-a23b2500-e4ec-11e8-8819-882996cbb966.png)

**Comment by avivace** [comment]
If you're still on this setup, can you retry and report back? 

I was able to remove any other remaining line or background I was seeing, is it fixed for you, too?

**Comment by nickdex** [comment]
I've moved to ArchLinux now
